-   type: TartanAirv2_NoIMU
    name: v2_H000
    args:
        root: /data2/datasets/yuhengq/tartanair_v2_test/Data_hard/P000
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAirv2_NoIMU
    name: v2_E000
    args:
        root: /data2/datasets/yuhengq/tartanair_v2_test/Data_easy/P000
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
