-   type: TartanAir_NoIMU
    name: SE000
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SE000
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SE001
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SE001
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SE002
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SE002
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SE003
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SE003
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SE004
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SE004
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SE005
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SE005
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SE006
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SE006
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SE007
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SE007
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SH000
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SH000
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SH001
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SH001
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SH002
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SH002
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SH003
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SH003
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SH004
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SH004
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SH005
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SH005
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SH006
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SH006
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
-   type: TartanAir_NoIMU
    name: SH007
    args:
        root: /data2/datasets/wenshanw/tartanair_test_release/stereo/SH007
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
